apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibge-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ibge-app
  template:
    metadata:
      labels:
        app: ibge-app
    spec:
      containers:
      - name: ibge-app
        image: darlonrsantos/ibge-app:1.0
        imagePullPolicy: IfNotPresent  # Alterar para "Never" se usando imagens locais no Minikube
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"