apiVersion: v1
kind: Service
metadata:
  name: ibge-service
spec:
  type: LoadBalancer  # Cria um IP externo
  selector:
    app: ibge-app
  ports:
    - protocol: TCP
      port: 80       # Porta externa
      targetPort: 5000  # Porta do container